[package]
name = "git-switch"
version = "1.0.5"
edition = "2024"

[dependencies]
console = "0.16"
dialoguer = { version = "0.12", features = ["fuzzy-select"] }
indicatif = "0.18"

[dev-dependencies]
tempfile = "3"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
